### ISSUE TITLE
Disallow duplicate fencers for pool sheet creation

### ISSUE THREAD

**Issue by chloe-buller** [UAHFencingClub/fencing-sport-lib#4]
Creating a new pool sheet using a vec allows for a fencer to be entered more than once into a pool sheet, causing panics during bout creation. Use an indexset instead.

**Comment by QuantumEF** [comment]
Fixed in https://github.com/UAHFencingClub/fencing-sport-lib/commit/4c69204c0860ac0a0b6ecf3095375182bd527ab0
